USE UNIVERSITY

DELETE STUDENTS FROM 
(SELECT STUDENTS.STUDENT_ID FROM STUDENTS, GROUPS
WHERE STUDENTS.GROUP_ID = GROUPS.GROUP_ID AND 
GROUPS.NAME = 'SR-01') AS SELECTED 
WHERE STUDENTS.STUDENT_ID = SELECTED.STUDENT_ID
