USE UNIVERSITY;

SELECT COURSES.NAME AS 'COURSE', STUDENTS.FIRST_NAME + ' '+ STUDENTS.LAST_NAME AS 'STUDENTS'
FROM COURSES
LEFT JOIN GROUPS ON COURSES.COURSE_ID = GROUPS.COURSE_ID
LEFT JOIN STUDENTS ON GROUPS.GROUP_ID = STUDENTS.GROUP_ID
ORDER BY 'COURSE'